# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='LikeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(verbose_name='IsLike')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_only.Answer', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
            ],
            options={
                'verbose_name': '\u041b\u0430\u0439\u043a \u043e\u0442\u0432\u0435\u0442\u0430',
                'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u043e\u0442\u0432\u0435\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='LikeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(verbose_name='IsLike')),
            ],
            options={
                'verbose_name': '\u041b\u0430\u0439\u043a \u0432\u043e\u043f\u0440\u043e\u0441\u0430',
                'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u0433',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('avatar', models.CharField(max_length=200, verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c',
                'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_only.UserProfile', verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='read_only.Tag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='likequestion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_only.UserProfile', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='likequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_only.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AddField(
            model_name='likeanswer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_only.UserProfile', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_only.UserProfile', verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_only.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
    ]
